apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: product-store
type: Opaque
stringData:
  CONNECTION_STRING: "Host=product-store-prod-postgres.cd80cs4iqule.ap-south-1.rds.amazonaws.com;Port=5432;Database=productstore;Username=sriya;Password=MusicPass123;SSL Mode=Require;Trust Server Certificate=true;"
  TOKEN: "tU6foF3dYL3CRWaysnkj5yQlWgPc050/3rrx6+8YaPUlOSE52Sc6A+iiCWdcehS9Dxc6SGhXPRk8xsku7CNoGw=="
