name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: checkout code
      uses: actions/checkout@v3

    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: login to ecr
      run: |
        aws ecr get-login-password --region ap-south-1 \
        | docker login --username AWS --password-stdin 661296494278.dkr.ecr.ap-south-1.amazonaws.com

    - name: build backend
      run: |
        docker build -t backend -f Backend/Backend/Dockerfile Backend/Backend
        docker tag backend:latest 661296494278.dkr.ecr.ap-south-1.amazonaws.com/product-store-prod-backend:latest

    - name: push backend
      run: |
        docker push 661296494278.dkr.ecr.ap-south-1.amazonaws.com/product-store-prod-backend:latest

    - name: build frontend
      run: |
        docker build -t frontend .
        docker tag frontend:latest 661296494278.dkr.ecr.ap-south-1.amazonaws.com/product-store-prod-frontend:latest

    - name: push frontend
      run: |
        docker push 661296494278.dkr.ecr.ap-south-1.amazonaws.com/product-store-prod-frontend:latest

    - name: setup kubectl
      run: |
        curl -o kubectl https://amazon-eks.s3.ap-south-1.amazonaws.com/1.29.0/2024-01-04/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: connect to eks
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name product-store-prod

    - name: restart deployments
      run: |
        kubectl rollout restart deployment backend -n product-store
        kubectl rollout restart deployment frontend -n product-store
